### ISSUE TITLE
Mislabel vector

### ISSUE THREAD

**Issue by matt2275** [jniedzie/LightByLight2018#2]
We were experiencing a seg fault with the latest update to this code and Georgios figured it is was because this line should be vector<int> instead of vector<bool> and it fixed the issue. Could you change this in your next commit. 

https://github.com/jniedzie/LightByLight2018/blob/4e433663ba49cda205b9462c9b83d384a9b9f4d5/analysis/include/EventProcessor.hpp#L71

**Comment by jniedzie** [comment]
Hi @matt2275,

thank you for spotting this issue! I committed a fix.

If you prefer, next time you want to introduce some changes/fixes, please feel free to create a PR.

Cheers,
Jeremi
